language: python
python:
- '2.7'
before_install:
- pwd
- sudo add-apt-repository ppa:dh-virtualenv/stable -y
- sudo apt-get update -qq
- sudo apt-get install -y --force-yes python python-pip python-virtualenv dh-virtualenv
  debhelper
install:
- pip install -r requirements.txt
script:
- nosetests
- dpkg-buildpackage -us -uc
- pwd
- mkdir -p dist/debian
- mv -v ../tuttle_* dist/debian/
- ls
- sudo dpkg -i dist/debian/tuttle_0.1-1_amd64.deb
- cd doc/examples/musketeers
- tuttle run
- cp characters_count.png workflow_execution_success
- cd ../../..
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CNw4FQYKEtQGl5rZH+N/p3d0w1PsVEvNEP46hLes4H5t12Vueh3D5zkz9HasTywZV1UVxa67sTLMuo063GJMJWBHs3hUo9QyHkbETz4PWsUEc1ayhlcP+I/IeNKyTXHoEj93hAYT1LDiApSEa5KKsUW1c188Z2L5G9Z2cFvpKfY=
  file: dist/debian/tuttle_0.1-1_amd64.deb
  skip_cleanup: true
  on:
    repo: abonnasseau/tuttle
    tags: true
