
addons:
  postgresql: "9.2"

services:
  - docker
  - postgresql
 
language: python

python:
- '2.7'

before_install:
- sudo add-apt-repository ppa:dh-virtualenv/stable -y
- sudo apt-get update -qq
- sudo apt-get install -y --force-yes python python-pip python-virtualenv dh-virtualenv build-essential fakeroot devscripts
  debhelper
# Install odbc
- sudo apt-get install unixodbc-bin unixodbc odbc-postgresql unixodbc-dev
- sudo odbcinst -i -d -f /usr/share/psqlodbc/odbcinst.ini.template
- sudo odbcinst -i -s -l -n tuttle_test_db -f ci/odbc.ini


install:
- pip install -r requirements-dev.txt
- psql -c 'CREATE DATABASE tuttle_test_db;' -U postgres


script:
# Running tests
- pip install .
- python tests/test_addons/test_hdfs.py install
- . tests/hadoop/vars.sh
- nosetests -v
# Making .deb package
- dpkg-buildpackage -us -uc
- mkdir -p dist/debian
- mv -v ../tuttle_* dist/debian/
- sudo dpkg -i dist/debian/tuttle_0.6-1_amd64.deb
# Be sure the .deb package works
- cd ci
- tuttle run -j 3
- cp world-cities.csv workflow_execution_success
- cp from-python workflow_execution_success2
- cp from-shell-or-batch workflow_execution_success3
- cd ..
# building docker image
- cd docker
- docker login -u "tuttle" -p "$DOCKER_PASS"
- docker build -t tuttle/tuttle:master .
# - docker tag tuttle/tuttle:master tuttle/tuttle:latest
- docker tag tuttle/tuttle:master tuttle/tuttle:v0.6-dev1
- docker push tuttle/tuttle
- docker logout
- cd ..

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BmKAsspBpvzC1aSlwPHwDkuPYKEAirfFL9yWCoveMefH5c2TU2xurI5W1Nig2beW8JV54rcgvPAIYOMUHaEnMcFBix6G3ze7kbhIw8sFLNP2c7OiQrd6u7QY6BpsxyEq7Z2Ef6aajm1Nyj5H2AEUR63t2VFCilwWj2Wdzr0Rh/8=
  file: dist/debian/tuttle_0.6-1_amd64.deb
  skip_cleanup: true
  on:
    repo: lexman/tuttle
    tags: true
