language: python
python:
  - "2.7"

before_install:
  - uname -a
  - sudo add-apt-repository ppa:dh-virtualenv/stable -y
  - sudo apt-get update -qq
  - apt-get install -y python python-pip python-virtualenv dh-virtualenv debhelper

# command to install dependencies
install:
    - "pip install -r requirements.txt"

# command to run tests
script:
    - nosetests
    # Creates the debian package
    - dpkg-buildpackage -us -uc
