language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y docker.io
  - uname -a

# command to install dependencies
install:
    - "pip install -r requirements.txt"

# command to run tests
script:
    - nosetests
    - sudo docker build -t lexman/package_tuttle .
    - sudo docker run -v ~/dev/tuttle/result:/dist/deb -t lexman/package_tuttle