language: python
python:
  - "2.7"
# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - apt-get install -y docker
# command to run tests
script:
    - nosetests
    - docker run dockerfile4deb