language: python

python:
- '2.7'

before_install:
- pwd
- sudo add-apt-repository ppa:dh-virtualenv/stable -y
- sudo apt-get update -qq
- sudo apt-get install -y --force-yes python python-pip python-virtualenv dh-virtualenv debhelper

install:
- pip install -r requirements.txt

script:
- nosetests
- dpkg-buildpackage -us -uc
- pwd
- ls
- mkdir dist
- cp ../tuttle_* dist/
- touch dist/tuttle_test
- sudo dpkg -i ../tuttle_0.1-1_amd64.deb
- cd doc/examples/musketeers
- tuttle run
- cp characters_count.png workflow_execution_success

env:
  matrix:
    secure: TilOO9Vy4fP2w5OzW2IjNoO82hmBzRxdyJ/ygWgiz4UaLrCWxPxcboZnn7VIumgepO2MrhU2i7PLWxyhW7Ch8AK2JRfcs0xYcoH8rn0C7dezu1QHTVf2AjuUVLRblsTbemI6gaAxuiQa8cTcOyb31UA/zn0ztGhthdP2OyKnTzw=

deploy:
  provider: releases
  api_key:
    secure: ZXFuh7l4dw2vHitMSk3XG4/k+30NoaPjlMj/VUmlXU37B60LRtOtPeyeuo0CptJ1j4Cll4cGsgGhYVahNMuIlJmtNWOZ5lOXtBE4fS9B8+Sa4Np8sc9nMJ3TWIeXBmgkKVREJKMTVhc7DeMTUgLQIIj6+KQlv3Au6LjDmqtXdcQ=
  file: dist/tuttle_0.1-1_amd64.deb
  on:
    repo: abonnasseau/tuttle
    tags: true
  skip_cleanup: true
