site_name: tuttle
theme: readthedocs
pages:
- Overview : index.md
- Reference :
    - reference/index.md
    - reference/tuttlefile_syntax.md
    - reference/resources_and_urls.md
    - reference/processors.md
    - reference/resources_authentication.md
- Tutorials:
    - Discover tuttle : tutorial_musketeers/tutorial.md
    - Parametrized workflow : tuto_parametrized_workflow/tuto_parametrized_workflow.MD
    - If you're familiar with Makefiles : tuto_Makefile.MD
- Developpers:
    - how_to_make_a_release.md
